services:
  pol-ler:
    platform: linux/amd64
    build:
      context: .
    environment:
      DB_NAME: 'politepol'
      DB_USER: 'rooooooooooot'
      DB_PASSWORD: 'toooooooooooor'
      DB_HOST: 'db-pol-ler'
      DB_PORT: '3306'
      WEB_PORT: '8088'
      TIME_ZONE: 'America\/Fortaleza'
    image: pol-ler:latest
    depends_on:
      - 'db-pol-ler'
    command: ["./wait-for-it.sh", "db-pol-ler", "/bin/bash", "./frontend/start.sh"]
    container_name: pol-ler
    restart: unless-stopped
    networks:
      - pol-ler-network
    ports:
      - '8088:8088'

  db-pol-ler:
    image: mysql:5.7
    platform: linux/amd64
    container_name: db-pol-ler
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'politepol'
      MYSQL_USER: 'rooooooooooot'
      MYSQL_PASSWORD: 'toooooooooooor'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    networks:
      - pol-ler-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  pol-ler-network:
    driver: 'bridge'
