apiVersion: v1
kind: Service
metadata:
  name: {{ include "pol-ler.fullname" . }}-postgres
  labels:
    {{- include "pol-ler.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "pol-ler.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres

