apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pol-ler.fullname" . }}-postgres
  labels:
    {{- include "pol-ler.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}

